apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eldocam-backend
  namespace: eldocam
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - api.eldocam.com
    secretName: eldocam-backend-tls
  rules:
  - host: api.eldocam.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eldocam-backend
            port:
              number: 80
