apiVersion: v1
kind: Service
metadata:
  name: eldocam-backend
  namespace: eldocam
spec:
  selector:
    app: eldocam-backend  # ⚠️ Doit matcher les labels du deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
